-- Prunerr telemetry — D1 schema.
--
-- One row per install, not one row per ping. That is the whole design:
-- a heartbeat is an UPSERT that moves `last_seen`, so the table never grows
-- beyond the number of installs that have ever reported, and the daily write
-- count equals the number of active installs rather than the number of pings.
-- It also means there is no ping history to leak, because none is kept.

CREATE TABLE IF NOT EXISTS installs (
  -- Random UUID generated by the Prunerr install. Not derived from anything.
  install_id TEXT PRIMARY KEY,
  -- The Prunerr version that last reported.
  version    TEXT NOT NULL,
  -- Unix seconds. Dates only, no request metadata: no IP, no user agent,
  -- no country, nothing that describes who sent it.
  first_seen INTEGER NOT NULL,
  last_seen  INTEGER NOT NULL
);

-- Every stats query filters on last_seen, and the row-read allowance on D1's
-- free plan counts rows *examined*, so this index is what keeps a full count
-- from scanning the table.
CREATE INDEX IF NOT EXISTS idx_installs_last_seen ON installs (last_seen);

-- Optional daily rollup, so a chart of "installs over time" survives the
-- retention prune. Holds counts only — no IDs.
CREATE TABLE IF NOT EXISTS daily_counts (
  day            TEXT PRIMARY KEY, -- YYYY-MM-DD (UTC)
  active_installs INTEGER NOT NULL,
  recorded_at    INTEGER NOT NULL
);
