// Type-safe translation keys for react-i18next (re-exports i18next's types).
// The `Resources` interface is auto-generated by `npm run i18n:types` into
// resources.d.ts and grows as each feature namespace is extracted — do not
// hand-edit the key list; edit the locale JSON and regenerate.
import 'i18next';
import type Resources from './resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: Resources;
  }
}
