// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "activityLog": {
    "chips": {
      "flagged_one": "{{count}} flagged",
      "flagged_other": "{{count}} flagged",
      "grace": "{{days}}d grace",
      "resetOverseerr": "Reset Seerr",
      "scanned_one": "{{count}} scanned",
      "scanned_other": "{{count}} scanned"
    },
    "empty": {
      "clearFilters": "Clear Filters",
      "desc": "System activity will appear here as scans run, rules match, and deletions occur.",
      "filteredDesc": "No activities match your current filters. Try adjusting your search terms or filter options.",
      "filteredTitle": "No matching activity",
      "title": "No activity yet"
    },
    "errors": {
      "loadFailed": "Failed to load activity log"
    },
    "filters": {
      "actorLabel": "Actor:",
      "dateRange": {
        "24h": "Last 24 hours",
        "30d": "Last 30 days",
        "7d": "Last 7 days",
        "all": "All time"
      },
      "dateRangeLabel": "Date range",
      "eventLabel": "Event:",
      "scanHiddenNotice": "Scan events are hidden by default.",
      "searchPlaceholder": "Search by target name...",
      "showAllEvents": "Show all events"
    },
    "formatter": {
      "byActor": "By {{actor}}",
      "collectionProtected": "Collection protected",
      "collectionUnprotected": "Collection unprotected",
      "deleted": "Deleted",
      "episodesDeleted_one": "{{count}} episode deleted",
      "episodesDeleted_other": "{{count}} episodes deleted",
      "episodesQueued_one": "{{count}} episode queued for deletion",
      "episodesQueued_other": "{{count}} episodes queued for deletion",
      "episodesUnmonitored_one": "{{count}} episode unmonitored",
      "episodesUnmonitored_other": "{{count}} episodes unmonitored",
      "episodesUnqueued_one": "{{count}} episode taken out of the queue",
      "episodesUnqueued_other": "{{count}} episodes taken out of the queue",
      "error": "Error",
      "flaggedForReview": "Flagged for review",
      "matchedRule": "Matched rule: {{rule}}",
      "protected": "Protected",
      "protectionRemoved": "Protection removed",
      "queuedForDeletion": "Queued for deletion",
      "reason": "Reason: {{reason}}",
      "removedFromQueue": "Removed from queue",
      "scanCompleted": "Library scan completed",
      "scanFailed": "Library scan failed",
      "scanStarted": "Library scan started",
      "unmonitored": "Unmonitored"
    },
    "header": {
      "subtitle": "System events and actions",
      "title": "Activity Log"
    },
    "pagination": {
      "pageOf": "Page {{page}} of {{total}}",
      "showing": "Showing {{from}} to {{to}} of {{total}} activities"
    },
    "table": {
      "actor": "Actor",
      "event": "Event",
      "target": "Target",
      "time": "Time"
    }
  },
  "collections": {
    "backToCollections": "Back to Collections",
    "badges": {
      "protected": "Protected",
      "synced": "Synced {{time}}",
      "tmdb": "TMDB {{id}}"
    },
    "card": {
      "itemCount_one": "{{count}} item",
      "itemCount_other": "{{count}} items"
    },
    "empty": {
      "clearSearch": "Clear search",
      "noMatchDesc": "No collections found matching \"{{search}}\"",
      "noMatchTitle": "No matching collections",
      "noneDesc": "Sync your collections from Radarr to get started.",
      "noneTitle": "No collections yet",
      "syncNow": "Sync Now"
    },
    "errors": {
      "loadCollection": "Failed to load collection",
      "loadFailed": "Failed to load collections"
    },
    "header": {
      "eyebrow": "Media Groups",
      "subtitle": "Manage your Radarr collections. Protect entire collections to prevent their items from being cleaned up.",
      "syncButton": "Sync Collections",
      "title": "Collections"
    },
    "itemType": {
      "movie": "Movie",
      "tv": "TV"
    },
    "items": {
      "emptyDesc": "This collection has no matched media items in your library.",
      "emptyTitle": "No items found",
      "heading_one": "Items ({{count}})",
      "heading_other": "Items ({{count}})",
      "loadFailed": "Failed to load items",
      "loading": "Loading items..."
    },
    "notFound": {
      "invalidIdDesc": "The collection ID in the URL is not valid.",
      "removedDesc": "This collection may have been removed.",
      "title": "Collection not found"
    },
    "protection": {
      "disabledDesc": "Enable protection to prevent items from being cleaned up.",
      "enabledDesc": "All items in this collection are protected from cleanup rules.",
      "protectButton": "Protect Collection",
      "reasonLabel": "Reason:",
      "reasonPlaceholder": "Reason (optional)",
      "removeButton": "Remove Protection",
      "title": "Collection Protection"
    },
    "queue": {
      "cancel": "Cancel",
      "confirm": "Confirm",
      "confirmPrompt_one": "This will queue <strong>{{count}} item</strong> for deletion. Are you sure?",
      "confirmPrompt_other": "This will queue <strong>{{count}} items</strong> for deletion. Are you sure?",
      "deletionActionLabel": "Deletion Action",
      "gracePeriodHelp": "Items will be deleted after this many days.",
      "gracePeriodLabel": "Grace Period (days)",
      "queueButton": "Queue Collection for Deletion",
      "resetSeerr": "Reset in Seerr",
      "subtitle": "Add all items in this collection to the deletion queue.",
      "title": "Queue for Deletion"
    },
    "search": {
      "placeholder": "Search collections..."
    },
    "toasts": {
      "protectedMsg": "\"{{title}}\" is now protected",
      "protectedTitle": "Collection protected",
      "protectionFailedTitle": "Failed to update protection",
      "protectionRemovedMsg": "\"{{title}}\" is no longer protected",
      "protectionRemovedTitle": "Protection removed",
      "queueFailedTitle": "Failed to queue collection",
      "queuedMsg_one": "Queued {{count}} item ({{size}})",
      "queuedMsg_other": "Queued {{count}} items ({{size}})",
      "queuedSkippedSuffix_one": ", {{count}} skipped",
      "queuedSkippedSuffix_other": ", {{count}} skipped",
      "queuedTitle": "Collection queued for deletion",
      "somethingWrong": "Something went wrong",
      "syncFailedMsg": "Failed to sync collections from Radarr",
      "syncFailedTitle": "Sync failed",
      "syncedTitle": "Collections synced"
    }
  },
  "common": {
    "dismissNotification": "Dismiss notification",
    "dropdown": {
      "noMatches": "No matches",
      "placeholder": "Select…",
      "search": "Search…"
    },
    "errors": {
      "forbidden": "You don't have permission to perform this action.",
      "network": "Unable to connect to the server. Please check your connection.",
      "notFound": "The requested resource was not found.",
      "server": "The server encountered an error. Please try again later.",
      "timeout": "The request took too long. Please try again.",
      "unexpected": "An unexpected error occurred. Please try again."
    },
    "language": {
      "label": "Language"
    },
    "relative": {
      "ago": "{{value}} ago",
      "in": "in {{value}}",
      "justNow": "just now"
    },
    "schedule": {
      "custom": "Custom schedule",
      "dailyAt": "Daily at {{time}}",
      "days": {
        "friday": "Friday",
        "monday": "Monday",
        "saturday": "Saturday",
        "sunday": "Sunday",
        "thursday": "Thursday",
        "tuesday": "Tuesday",
        "wednesday": "Wednesday"
      },
      "everyHour": "Every hour",
      "everyMinute": "Every minute",
      "everyNHours_one": "Every {{count}} hour",
      "everyNHours_other": "Every {{count}} hours",
      "everyNMinutes_one": "Every {{count}} minute",
      "everyNMinutes_other": "Every {{count}} minutes",
      "monthlyAt": "Monthly on day {{day}} at {{time}}",
      "weeklyAt": "Every {{day}} at {{time}}"
    },
    "telemetry": {
      "dismiss": "Dismiss",
      "gotIt": "Got it",
      "noticeBody": "Once a day, Prunerr sends a random ID and its version number so we can see how many people are using it. That is all it sends — nothing about your library, your settings or you.",
      "noticeTitle": "Anonymous install count",
      "turnOff": "Turn it off"
    },
    "timeline": {
      "action": {
        "addedToPlex": "Added to Plex",
        "collectionProtected": "Collection protected",
        "collectionUnprotected": "Collection unprotected",
        "episodesDeleted_one": "{{count}} episode deleted",
        "episodesDeleted_other": "{{count}} episodes deleted",
        "episodesFailed_one": "{{count}} episode download failed",
        "episodesFailed_other": "{{count}} episode downloads failed",
        "episodesGrabbed_one": "{{count}} episode sent to the downloader",
        "episodesGrabbed_other": "{{count}} episodes sent to the downloader",
        "episodesImported_one": "{{count}} episode downloaded",
        "episodesImported_other": "{{count}} episodes downloaded",
        "episodesQueued_one": "{{count}} episode queued for deletion",
        "episodesQueued_other": "{{count}} episodes queued for deletion",
        "episodesRemovedInSonarr_one": "{{count}} episode file removed in Sonarr",
        "episodesRemovedInSonarr_other": "{{count}} episode files removed in Sonarr",
        "episodesUnmonitored_one": "{{count}} episode unmonitored",
        "episodesUnmonitored_other": "{{count}} episodes unmonitored",
        "episodesUnqueued_one": "{{count}} episode taken out of the queue",
        "episodesUnqueued_other": "{{count}} episodes taken out of the queue",
        "episodesUpgraded_one": "{{count}} episode upgraded",
        "episodesUpgraded_other": "{{count}} episodes upgraded",
        "firstScanned": "First scanned by Prunerr",
        "itemDeleted": "Deleted",
        "itemQueued": "Queued for deletion",
        "itemRestored": "Restored",
        "protected": "Item protected",
        "ruleMatched": "Matched by rule",
        "scanned": "Library scan",
        "unprotected": "Item unprotected"
      },
      "actor": {
        "rule": "Rule",
        "scheduler": "Scheduler",
        "user": "User"
      }
    },
    "unraid": {
      "arrayState": {
        "started": "Started",
        "stopped": "Stopped",
        "syncing": "Syncing",
        "unknown": "Unknown"
      }
    }
  },
  "dashboard": {
    "activity": {
      "emptyDesc": "Activity will appear here as you scan your library and manage media. Run a library sync to get started.",
      "emptyTitle": "No recent activity",
      "moreLink_one": "+{{count}} more — View activity log",
      "moreLink_other": "+{{count}} more — View activity log",
      "subtitle": "Latest actions and events",
      "title": "Recent Activity"
    },
    "chart": {
      "librarySizeOver_one": "Library size over {{count}} day",
      "librarySizeOver_other": "Library size over {{count}} days",
      "title": "Storage Trends",
      "total": "Total",
      "totalLibrarySize": "Total library size"
    },
    "deletions": {
      "emptyDesc": "No items are scheduled for deletion. Media flagged by rules or manually queued will appear here.",
      "emptyTitle": "Queue is clear",
      "subtitle": "Items scheduled for removal",
      "title": "Upcoming Deletions"
    },
    "disk": {
      "freeSuffix": "{{size}} free"
    },
    "diskGroups": {
      "array": "Array",
      "cache": "Cache",
      "parity": "Parity"
    },
    "errors": {
      "activity": "Failed to load activity",
      "dashboard": "Failed to load dashboard",
      "deletions": "Failed to load deletions",
      "recommendations": "Failed to load recommendations",
      "storage": "Failed to load storage info"
    },
    "header": {
      "lastScan": "Last scan:",
      "never": "Never",
      "overview": "Overview",
      "subtitle": "Monitor your media library health and cleanup progress",
      "title": "Dashboard"
    },
    "quickStats": {
      "activeRules": "Active Rules",
      "collections": "Collections",
      "reclaimedWeek": "Space Reclaimed This Week",
      "scannedToday": "Items Scanned Today"
    },
    "recCard": {
      "queueForDeletion": "Queue for Deletion"
    },
    "recommended": {
      "emptyDesc": "No stale content found based on your watch history. Items unwatched for 90+ days will appear here.",
      "emptyTitle": "Library is in great shape!",
      "reclaimableSuffix": " • {{size}} reclaimable",
      "subtitle_one": "{{count}} item hasn't been watched in 90+ days",
      "subtitle_other": "{{count}} items haven't been watched in 90+ days",
      "title": "Recommended for Cleanup"
    },
    "services": {
      "overseerr": "Request management",
      "plex": "Media server for library data",
      "radarr": "Movie management and deletion",
      "sonarr": "TV show management and deletion",
      "unraid": "Server storage monitoring",
      "watchHistory": "Watch history and statistics"
    },
    "stats": {
      "episodes_one": "{{count}} episode",
      "episodes_other": "{{count}} episodes",
      "itemsQueued_one": "{{count}} item queued",
      "itemsQueued_other": "{{count}} items queued",
      "movies": "Movies",
      "reclaimable": "Reclaimable",
      "totalStorage": "Total Storage",
      "tvShows": "TV Shows",
      "unwatched_one": "{{count}} unwatched",
      "unwatched_other": "{{count}} unwatched",
      "usedSuffix": "{{size}} used"
    },
    "storage": {
      "arrayState": "Array State",
      "cacheStorage": "Cache Storage",
      "ofTotal": "of {{total}}",
      "subtitle": "Unraid server disk statistics",
      "title": "Storage Overview",
      "updated": "Updated {{time}}"
    },
    "toasts": {
      "arrNotConfiguredMsg": "Set up Sonarr or Radarr in Settings to enable deletion.",
      "arrNotConfiguredTitle": "Sonarr/Radarr not configured",
      "failedQueueMsg": "Failed to queue \"{{title}}\"",
      "failedQueueTitle": "Failed to queue",
      "queuedMsg": "\"{{title}}\" added to deletion queue",
      "queuedTitle": "Queued for deletion"
    },
    "viewAll": "View all",
    "welcome": {
      "configureService": "Configure {{name}}",
      "configureServices": "Configure Services",
      "groupAtLeastOne": "At Least One",
      "groupOptional": "Optional",
      "groupRequired": "Required",
      "groupWatchHistory": "Watch History (one)",
      "readyMessage": "Required services configured! You're ready to go.",
      "reviewSettings": "Review Settings",
      "servicesCount": "{{configured}} of {{total}} services",
      "setupProgress": "Setup Progress",
      "subtitle": "Let's get your media library cleanup system configured. Connect your services below to get started.",
      "title": "Welcome to Prunerr"
    }
  },
  "health": {
    "caption": {
      "avgSummary_one": "avg {{mean}} · {{count}}d",
      "avgSummary_other": "avg {{mean}} · {{count}}d",
      "filesPruned": "Files pruned <1>per scan</1>"
    },
    "card": {
      "enabled": "enabled",
      "paused": "paused",
      "title": "Schedule"
    },
    "empty": {
      "loading": "Loading scan history…",
      "noPrunedSub": "Scans are running {{schedule}}. Items matching your rules are queued and will be pruned once their grace period passes — this chart fills in as deletions happen.",
      "noPrunedTitle": "No files pruned yet",
      "noScansSub": "Runs automatically {{schedule}} — or run one now to check your library against all enabled rules.",
      "noScansTitle": "No scans yet"
    },
    "footer": {
      "lastScan": "Last scan",
      "neverRun": "Never run",
      "nextRun": "Next run",
      "paused": "Paused"
    },
    "header": {
      "refreshing": "Refreshing...",
      "title": "Service Status"
    },
    "overall": {
      "degraded": "Partial Outage",
      "healthy": "All Systems Operational",
      "unhealthy": "Systems Unavailable"
    },
    "scan": {
      "buttonTitle": "Scan now — check the library against all enabled rules",
      "now": "Scan now",
      "scanning": "Scanning…"
    },
    "service": {
      "checking": "Checking...",
      "configureService": "Configure {{name}}",
      "connected": "Connected",
      "disconnected": "Disconnected",
      "notConfigured": "Not configured",
      "openService": "Open {{name}}"
    },
    "toasts": {
      "scanCompleteMsg": "The schedule chart has been updated.",
      "scanCompleteTitle": "Scan complete",
      "scanStartFailedMsg": "Could not start the scan.",
      "scanStartFailedTitle": "Scan failed to start",
      "scanStartedMsg": "Checking your library against all enabled rules…",
      "scanStartedTitle": "Scan started"
    },
    "tooltip": {
      "failed": "Run failed — retried",
      "filesPruned": "files pruned",
      "flagged": "flagged for deletion",
      "gbFreed": "{{gb}} GB freed",
      "noScan": "No scan",
      "nothingToPrune": "Nothing to prune"
    }
  },
  "history": {
    "empty": {
      "clearFilters": "Clear Filters",
      "desc": "Items you delete will appear here for your records. Process your deletion queue to start tracking cleanup activity.",
      "filteredDesc": "No deleted items match your search or date range. Try different search terms or adjust the date filter.",
      "filteredTitle": "No matching history",
      "title": "No deletion history"
    },
    "errors": {
      "loadFailed": "Failed to load history"
    },
    "export": {
      "placeholder": "Export functionality would download a CSV of deletion history"
    },
    "filters": {
      "allTime": "All time",
      "dateRangeLabel": "Date range",
      "last30Days": "Last 30 days",
      "last7Days": "Last 7 days",
      "last90Days": "Last 90 days",
      "searchPlaceholder": "Search deleted items..."
    },
    "header": {
      "exportCsv": "Export CSV",
      "subtitle": "Log of all deleted media items",
      "title": "Deletion History"
    },
    "pagination": {
      "pageOf": "Page {{page}} of {{totalPages}}",
      "showing": "Showing {{from}} to {{to}} of {{total}} items"
    },
    "reason": {
      "manual": "Manual",
      "rule": "Rule: {{rule}}",
      "unknown": "Unknown"
    },
    "stats": {
      "spaceReclaimed": "Space Reclaimed",
      "totalDeleted": "Total Items Deleted"
    },
    "table": {
      "deleted": "Deleted",
      "item": "Item",
      "reason": "Reason",
      "size": "Size",
      "type": "Type"
    }
  },
  "layout": {
    "closeMenu": "Close navigation menu",
    "diskStats": {
      "allHealthy": "All healthy",
      "array": "Array",
      "arrayMap": "Array map",
      "cache": "Cache",
      "capacityComposition": "Capacity composition",
      "description": "Live storage breakdown from your Unraid server",
      "diskFree": "{{size}} free",
      "disks": "Disks",
      "disksIdle_one": "{{count}} disk idle",
      "disksIdle_other": "{{count}} disks idle",
      "drivesRaw_one": "{{count}} drive · {{size}} raw",
      "drivesRaw_other": "{{count}} drives · {{size}} raw",
      "free": "Free",
      "genericError": "An error occurred",
      "growthSub": "at +{{rate}} TB/mo",
      "idle": "idle",
      "invalid": "Invalid",
      "lastParityCheck": "Last parity check",
      "legendArray": "Array",
      "legendCache": "Cache",
      "legendFree": "Free",
      "loadError": "Unable to load disk statistics",
      "loading": "Loading disk statistics…",
      "monthsValue_one": "{{count}} month",
      "monthsValue_other": "{{count}} months",
      "notConfigured": "Unraid not configured",
      "notConfiguredHint": "Configure your Unraid connection in Settings to view detailed disk statistics.",
      "parity": "Parity",
      "projectedFull": "Projected full",
      "protected": "Protected",
      "smart": "SMART",
      "title": "Disk Statistics",
      "trend12mo": "12-month trend",
      "updated": "Updated {{time}}",
      "usedCapacity": "Used capacity",
      "warningsValue_one": "{{count}} warning",
      "warningsValue_other": "{{count}} warnings",
      "zeroErrors": "0 errors"
    },
    "links": {
      "dockerHub": "Docker Hub",
      "github": "GitHub",
      "unraidSupport": "Unraid Support",
      "website": "Website",
      "websiteAria": "Prunerr website"
    },
    "menuLabel": "Menu",
    "nav": {
      "activity": "Activity",
      "collections": "Collections",
      "dashboard": "Dashboard",
      "history": "History",
      "library": "Library",
      "queue": "Queue",
      "rules": "Rules",
      "settings": "Settings"
    },
    "openMenu": "Open navigation menu",
    "storage": {
      "connectPrompt": "Connect Unraid to monitor",
      "freeSuffix": "{{size}} free",
      "growingTooltip": "Growing {{amount}} TB / month",
      "label": "Storage",
      "ofTotal": "of {{total}}",
      "shrinkingTooltip": "Shrinking {{amount}} TB / month"
    },
    "tagline": "Media Library Manager",
    "theme": {
      "toDark": "Switch to dark mode",
      "toLight": "Switch to light mode"
    },
    "whatsNew": {
      "buttonUnread_one": "What's new, {{count}} unread",
      "buttonUnread_other": "What's new, {{count}} unread",
      "close": "Close",
      "disabled": "Announcements are off because the anonymous install count is off. Turn it on under Settings → Privacy to receive them.",
      "disabledByEnv": "Announcements are off for this container (TELEMETRY_ENABLED=false).",
      "empty": "Nothing to show yet.",
      "loadFailed": "Could not load what’s new.",
      "offline": "Announcements could not be fetched. Check back later.",
      "readMore": "Read more",
      "refresh": "Check for announcements",
      "showLess": "Show less",
      "title": "What's new",
      "type": {
        "announcement": "Announcement",
        "feature": "New",
        "feedback": "Your feedback",
        "fix": "Fixed",
        "improvement": "Improved"
      },
      "unread": "New"
    }
  },
  "library": {
    "card": {
      "individuallyProtected": "Individually protected",
      "neverWatched": "Never watched",
      "plays_one": "{{count}} play",
      "plays_other": "{{count}} plays",
      "protectedVia": "Via: {{title}}"
    },
    "deletionModal": {
      "arrNotConfiguredDesc": "Items can be queued but won't be deleted from disk until Sonarr or Radarr is set up in Settings.",
      "arrNotConfiguredTitle": "Sonarr/Radarr not configured",
      "cancel": "Cancel",
      "daysBeforeDeletion": "days before deletion",
      "deletionAction": "Deletion Action",
      "description": "Configure how this content should be handled when the grace period expires.",
      "graceHelpDelayed_one": "Item will be deleted after {{count}} day.",
      "graceHelpDelayed_other": "Item will be deleted after {{count}} days.",
      "graceHelpImmediate": "Item will be eligible for immediate deletion when the queue is processed.",
      "gracePeriod": "Grace Period",
      "processing": "Processing...",
      "resetInSeerr": "Reset in Seerr",
      "resetInSeerrDesc": "Allow this content to be re-requested in Seerr after deletion",
      "seerr": "Seerr",
      "titleCount_one": "Mark {{count}} Item for Deletion",
      "titleCount_other": "Mark {{count}} Items for Deletion",
      "titleSingle": "Mark \"{{title}}\" for Deletion"
    },
    "detail": {
      "activityTimeline": "Activity Timeline",
      "added": "Added",
      "backToLibrary": "Back to Library",
      "codec": "Codec",
      "detailsHeading": "Details",
      "fileSize": "File Size",
      "lastWatched": "Last Watched",
      "loadFailedDesc": "An error occurred while loading this item.",
      "loadFailedTitle": "Failed to load item",
      "never": "Never",
      "notFoundDesc": "This media item could not be found. It may have been deleted.",
      "notFoundTitle": "Item not found",
      "playCount": "Play Count",
      "protectedVia": "Protected via {{title}}",
      "protectionReason": "Protection Reason",
      "resolution": "Resolution",
      "returnToLibrary": "Return to Library",
      "scheduledDeletion": "Scheduled Deletion",
      "sections": {
        "activity": "Activity",
        "details": "Details",
        "episodes": "Episodes"
      },
      "unknown": "Unknown",
      "watchedBy": "Watched By"
    },
    "empty": {
      "clearFilters": "Clear Filters",
      "clearSearch": "Clear Search",
      "filtersDesc": "Try adjusting your type or status filters to see more items.",
      "filtersTitle": "No items match filters",
      "libraryDesc": "Sync your library to import media from Plex and start managing your collection.",
      "libraryTitle": "Your library is empty",
      "searchDesc": "No media matching \"{{search}}\" was found. Try a different search term or clear filters.",
      "searchTitle": "No results found",
      "syncLibrary": "Sync Library"
    },
    "episodeDeletion": {
      "actions": {
        "deleteFilesOnly": "Delete the episode files; Sonarr keeps monitoring and may grab them again",
        "unmonitorAndDelete": "Delete the episode files and stop Sonarr grabbing them again",
        "unmonitorOnly": "Stop Sonarr monitoring these episodes but keep the files on disk"
      },
      "confirmNow": "Delete now",
      "confirmQueue": "Queue for deletion",
      "description": "Sonarr handles the selected episodes; the rest of the series is untouched.",
      "graceHelpDelayed_one": "Episodes stay on disk for {{count}} day and can be taken back out of the queue at any point.",
      "graceHelpDelayed_other": "Episodes stay on disk for {{count}} days and can be taken back out of the queue at any point.",
      "graceHelpImmediate": "Episodes will be deleted the next time the queue is processed.",
      "immediateDesc": "The selected episodes are handled in Sonarr right away, with no grace period to cancel within.",
      "immediateTitle": "This runs immediately",
      "selected_one": "{{count}} episode selected",
      "selected_other": "{{count}} episodes selected",
      "titleNow_one": "Delete {{count}} episode now",
      "titleNow_other": "Delete {{count}} episodes now",
      "titleQueue_one": "Queue {{count}} episode for deletion",
      "titleQueue_other": "Queue {{count}} episodes for deletion",
      "toastCancelFailed": "Could not cancel",
      "toastCancelled": "Removed from the queue",
      "toastCancelledMsg_one": "{{count}} episode will be kept",
      "toastCancelledMsg_other": "{{count}} episodes will be kept",
      "toastDeleted": "Episodes deleted",
      "toastDeletedMsg_one": "Deleted {{count}} episode, freeing {{size}}",
      "toastDeletedMsg_other": "Deleted {{count}} episodes, freeing {{size}}",
      "toastFailed": "Could not delete episodes",
      "toastQueued": "Episodes queued",
      "toastQueuedMsg_one": "Queued {{count}} episode for deletion",
      "toastQueuedMsg_other": "Queued {{count}} episodes for deletion"
    },
    "errors": {
      "loadLibrary": "Failed to load library"
    },
    "filters": {
      "all": "All",
      "allStatus": "All Status",
      "deleted": "Deleted",
      "movies": "Movies",
      "queued": "Queued",
      "resultCount_one": "{{count}} result",
      "resultCount_other": "{{count}} results",
      "searchPlaceholder": "Search movies, shows...",
      "statusLabel": "Status",
      "tvShows": "TV Shows",
      "unwatched": "Unwatched",
      "watched": "Watched"
    },
    "header": {
      "eyebrow": "Browse",
      "itemCount_one": "{{count}} item in your collection",
      "itemCount_other": "{{count}} items in your collection",
      "syncLibrary": "Sync Library",
      "syncing": "Syncing...",
      "title": "Media Library"
    },
    "mediaType": {
      "movie": "Movie",
      "tvShow": "TV Show"
    },
    "menu": {
      "markForDeletion": "Mark for Deletion",
      "openIn": "Open in",
      "protect": "Protect",
      "protectItem": "Protect Item",
      "removeProtection": "Remove Protection"
    },
    "pagination": {
      "showing": "Showing <0>{{from}}</0> to <1>{{to}}</1> of <2>{{total}}</2> items"
    },
    "selection": {
      "addToQueue": "Add to Queue",
      "clear": "Clear selection",
      "itemsSelected": "items selected",
      "protect": "Protect",
      "queue": "Queue",
      "unprotect": "Unprotect"
    },
    "sonarr": {
      "completion": "Library completion",
      "continuing": "Continuing",
      "downloadingCount_one": "{{count}} downloading",
      "downloadingCount_other": "{{count}} downloading",
      "ended": "Ended",
      "eta": "Done {{when}}",
      "file": {
        "added": "Imported",
        "audio": "Audio",
        "languages": "Languages",
        "path": "File",
        "releaseGroup": "Release group",
        "runtime": "Runtime",
        "subtitles": "Subtitles",
        "video": "Video"
      },
      "filter": {
        "all": "All episodes",
        "downloading": "Downloading",
        "missing": "Missing",
        "queued": "Queued",
        "upgradable": "Upgradable"
      },
      "heading": "Sonarr",
      "missingCount_one": "{{count}} missing",
      "missingCount_other": "{{count}} missing",
      "monitored": "Monitored",
      "nextAiring": "Next episode {{when}}",
      "noAirDate": "No air date",
      "noEpisodes": "No episodes in this season yet.",
      "noSeasons": "Sonarr has no seasons for this series yet.",
      "notConfigured": "Connect Sonarr in Settings to see episode-level detail for this show.",
      "notLinked": "This show is not matched to a series in Sonarr, so there is no episode detail to show.",
      "queuedCount_one": "{{count}} queued",
      "queuedCount_other": "{{count}} queued",
      "queuedIn": "Deletes {{when}}",
      "season": "Season {{number}}",
      "selection": {
        "cancelQueued_one": "Cancel deletion ({{count}})",
        "cancelQueued_other": "Cancel deletion ({{count}})",
        "clear": "Clear",
        "clearAll": "Clear selection",
        "deleteNow": "Delete now",
        "label_one": "episode selected",
        "label_other": "episodes selected",
        "queue": "Queue for deletion",
        "selectAll": "Select every listed episode",
        "selectAllLabel_one": "Select all {{count}} episodes",
        "selectAllLabel_other": "Select all {{count}} episodes",
        "selectEpisode": "Select {{title}}",
        "selectSeason": "Select the listed episodes in {{season}}",
        "shiftHint": "Shift-click to select a range across seasons"
      },
      "specials": "Specials",
      "state": {
        "downloaded": "Downloaded",
        "downloading": "Downloading",
        "missing": "Missing",
        "unaired": "Not aired",
        "unmonitored": "Unmonitored"
      },
      "stats": {
        "downloading_one": "{{count}} downloading",
        "downloading_other": "{{count}} downloading",
        "episodes": "Episodes on disk",
        "episodesValue": "{{files}} of {{aired}} aired",
        "missing": "Missing episodes",
        "onDisk": "Size on disk",
        "seasons_one": "{{count}} season",
        "seasons_other": "{{count}} seasons",
        "upgradable": "Below quality cutoff"
      },
      "unmonitored": "Unmonitored",
      "unreachable": "Could not reach Sonarr. Check the connection in Settings.",
      "updated": "updated {{when}}",
      "upgradable": "Upgradable"
    },
    "status": {
      "active": "Active",
      "deleted": "Deleted",
      "protected": "Protected",
      "queued": "Queued",
      "queuedForDeletion": "Queued for Deletion"
    },
    "table": {
      "lastWatched": "Last Watched",
      "noItemsFound": "No items found",
      "size": "Size",
      "status": "Status",
      "title": "Title",
      "type": "Type",
      "watched": "Watched"
    },
    "timeline": {
      "emptyDesc": "Actions like queuing, protecting, and rule matches will appear here.",
      "emptyTitle": "No activity recorded for this item yet",
      "hideEpisodes": "Hide episodes",
      "showEpisodes_one": "Show {{count}} episode",
      "showEpisodes_other": "Show {{count}} episodes"
    },
    "toasts": {
      "addedToQueueMsg_one": "{{count}} item added to deletion queue",
      "addedToQueueMsg_other": "{{count}} item(s) added to deletion queue",
      "addedToQueueTitle": "Added to queue",
      "addedToQueueWithSkipped_one": "{{count}} item added to deletion queue, {{skipped}} skipped",
      "addedToQueueWithSkipped_other": "{{count}} item(s) added to deletion queue, {{skipped}} skipped",
      "failedAddToQueueTitle": "Failed to add to queue",
      "failedProtectTitle": "Failed to protect items",
      "genericError": "An error occurred",
      "itemsProtectedMsg_one": "{{count}} item protected",
      "itemsProtectedMsg_other": "{{count}} item(s) protected",
      "itemsProtectedTitle": "Items protected",
      "itemsProtectedWithSkipped_one": "{{count}} item protected, {{skipped}} already protected",
      "itemsProtectedWithSkipped_other": "{{count}} item(s) protected, {{skipped}} already protected",
      "protectionRemovedTitle": "Protection removed",
      "syncCompleteMsg": "{{scanned}} items scanned, {{synced}} synced",
      "syncCompleteTitle": "Library sync complete",
      "syncErrorTitle": "Sync error",
      "syncFailedTitle": "Sync failed",
      "syncGenericError": "An error occurred while syncing",
      "unprotectedMsg_one": "{{count}} item unprotected",
      "unprotectedMsg_other": "{{count}} item(s) unprotected"
    }
  },
  "queue": {
    "actions": {
      "cancel": "Cancel",
      "close": "Close",
      "confirmDelete": "Confirm Delete",
      "deleteAll": "Delete All",
      "deleteAllNow": "Delete All Now",
      "deleting": "Deleting...",
      "noItemsPastGrace": "No items have passed their grace period yet",
      "process": "Process",
      "processQueue": "Process Queue",
      "processing": "Processing...",
      "removeSelected_one": "Remove Selected ({{count}})",
      "removeSelected_other": "Remove Selected ({{count}})",
      "removingProgress": "Removing {{current}}/{{total}}..."
    },
    "arrWarning": {
      "bannerDesc": "Deletion requires Sonarr or Radarr to remove files from disk. Items can be queued but won't be processed until a service is set up.",
      "goToSettings": "Go to Settings",
      "modalDesc": "Items will be marked as deleted in Prunerr but files won't be removed from disk. Set up Sonarr or Radarr in Settings first.",
      "title": "Sonarr/Radarr not configured"
    },
    "deleteAllModal": {
      "summary_one": "{{count}} item will be deleted ({{size}})",
      "summary_other": "{{count}} item(s) will be deleted ({{size}})",
      "title": "Delete All Items Now",
      "warning": "This will permanently delete all items in the queue, ignoring grace periods."
    },
    "deleteNowModal": {
      "actionLabel": "Action:",
      "complete": "Deletion complete!",
      "fileProgress": "File {{current}} of {{total}}",
      "freed": "Freed {{size}}",
      "initializing": "Initializing...",
      "resetInSeerrSuffix": " • Reset in Seerr",
      "title": "Delete Now",
      "titleDeleting": "Deleting...",
      "warning": "This will immediately and permanently delete this item, bypassing the grace period.",
      "willResetSeerr": "Will reset in Seerr for re-request"
    },
    "empty": {
      "browseLibrary": "Browse Library",
      "description": "No items are currently marked for deletion. Browse your library to queue items for cleanup, or set up rules to automate the process.",
      "setUpRules": "Set up rules",
      "title": "Queue is empty"
    },
    "errors": {
      "loadQueue": "Failed to load queue"
    },
    "header": {
      "subtitle": "Items marked for deletion with grace period countdown",
      "title": "Deletion Queue"
    },
    "pagination": {
      "next": "Next",
      "previous": "Previous"
    },
    "processModal": {
      "readySummary_one": "{{ready}} of {{total}} item ready ({{size}})",
      "readySummary_other": "{{ready}} of {{total}} item(s) ready ({{size}})",
      "title": "Process Deletion Queue",
      "warning": "This will delete items that have passed their grace period."
    },
    "row": {
      "daysLeftShort_one": "{{count}}d left",
      "daysLeftShort_other": "{{count}}d left",
      "daysLeft_one": "{{count}} day left",
      "daysLeft_other": "{{count}} days left",
      "deleteNow": "Delete now",
      "deleteNowDisabled": "Configure Sonarr/Radarr in Settings to enable deletion",
      "deletesOn": "Deletes {{date}}",
      "episode": "episode",
      "protect": "Protect",
      "queued": "Queued {{time}}",
      "ready": "Ready",
      "readyToDelete": "Ready to Delete",
      "remove": "Remove",
      "removeFromQueue": "Remove from queue",
      "requestedBy": "Requested by: {{user}}",
      "reset": "Reset",
      "rulePrefix": "Rule: {{rule}}",
      "viewDetails": "View details",
      "viewInSeerr": "View in Seerr",
      "willResetIn": "Will reset in"
    },
    "stats": {
      "itemsInQueue": "Items in Queue",
      "readyToDelete": "Ready to Delete",
      "spaceToReclaim": "Space to Reclaim",
      "willResetSeerr": "Will Reset Seerr"
    },
    "table": {
      "selectAll": "Select All",
      "selectedCount_one": "{{count}} of {{total}} selected",
      "selectedCount_other": "{{count}} of {{total}} selected",
      "showingRange": "Showing {{start}}-{{end}} of {{total}}"
    },
    "toasts": {
      "deleteFailedMsg": "Failed to delete item",
      "deleteFailedTitle": "Delete failed",
      "deletedSuccessMsg": "\"{{title}}\" has been deleted ({{size}} freed)",
      "deletedSuccessTitle": "Deleted successfully",
      "itemsRemovedMsg_one": "{{count}} item removed from queue",
      "itemsRemovedMsg_other": "{{count}} item(s) removed from queue",
      "itemsRemovedTitle": "Items removed",
      "someItemsFailedMsg_one": "{{count}} item could not be removed",
      "someItemsFailedMsg_other": "{{count}} item(s) could not be removed",
      "someItemsFailedTitle": "Some items failed"
    }
  },
  "recommendations": {
    "card": {
      "protect": "Protect",
      "queue": "Queue"
    },
    "empty": {
      "description": "Your library is well-maintained! Items that haven't been watched in a while will appear here as suggestions.",
      "title": "No recommendations"
    },
    "filters": {
      "daysOption_one": "{{count}} day",
      "daysOption_other": "{{count}} days",
      "label": "Unwatched for at least:",
      "oneYear": "1 year"
    },
    "header": {
      "back": "Back to Dashboard",
      "eyebrow": "Smart Cleanup",
      "savingsLabel": "Potential space savings",
      "subtitle_one": "{{count}} item hasn't been watched in {{days}}+ days",
      "subtitle_other": "{{count}} items haven't been watched in {{days}}+ days",
      "title": "Recommended for Cleanup"
    },
    "pagination": {
      "pageOf": "Page {{page}} of {{totalPages}}"
    },
    "summary": {
      "reclaimableSpace": "Reclaimable Space",
      "threshold": "Threshold",
      "thresholdDays_one": "{{count}} day",
      "thresholdDays_other": "{{count}} days",
      "totalItems": "Total Items"
    }
  },
  "rules": {
    "alerts": {
      "treeTooDeep": "Condition tree is too deep (max {{max}} levels of nesting). Please simplify."
    },
    "builder": {
      "cancel": "Cancel",
      "close": "Close",
      "create": "Create",
      "createTitle": "Create Rule",
      "editTitle": "Edit Rule",
      "saving": "Saving...",
      "savingShort": "Saving…",
      "update": "Update",
      "updateRule": "Update Rule"
    },
    "card": {
      "active": "Active",
      "allMedia": "All Media",
      "conditionCount_one": "{{count}} condition",
      "conditionCount_other": "{{count}} condition",
      "conditionsHeading": "Conditions",
      "enableToRun": "Enable rule to run",
      "gracePeriodDays_one": "{{count}} day",
      "gracePeriodDays_other": "{{count}} days",
      "gracePeriodLabel": "Grace period:",
      "inactive": "Inactive",
      "libraryKey": "Library {{key}}",
      "priorityTooltip": "Rule priority (higher wins)",
      "runNow": "Run rule now",
      "v1Tooltip": "v1 legacy rule",
      "v2Tooltip": "v2 nested-group rule"
    },
    "collection": {
      "noValueNeeded": "(no value needed)",
      "protectedBadge": "Protected",
      "search": "Search collections…",
      "select": "Select collection…"
    },
    "condText": {
      "addedBefore": "Added before {{val}}",
      "addedGt": "Added more than {{val}} days ago",
      "daysSinceAdded": "Days since added {{op}} {{val}}",
      "daysSinceWatched": "Days since watched {{op}} {{val}}",
      "generic": "{{field}} {{op}} {{val}}",
      "lastWatchedGt": "Last watched more than {{val}} days ago",
      "neverWatched": "Never watched",
      "opGreaterThan": "greater than",
      "opIs": "is",
      "opLessThan": "less than",
      "playCount": "Play count {{op}} {{val}}",
      "sizeGt": "File size larger than {{val}} GB",
      "sizeOp": "File size {{op}} {{val}} GB",
      "unwatchedDays": "Unwatched for more than {{val}} days",
      "watchedOnce": "Watched exactly once"
    },
    "confirm": {
      "deleteRule": "Are you sure you want to delete this rule?"
    },
    "custom": {
      "appliesTo": "Applies to",
      "movies": "Movies",
      "ruleNamePlaceholder": "e.g., Clean up low-rated old movies",
      "tvShows": "TV Shows"
    },
    "deletionActions": {
      "delete_files_only": {
        "description": "Delete the media files but keep the item in Sonarr/Radarr for re-download",
        "label": "Delete Files Only"
      },
      "full_removal": {
        "description": "Completely remove from Sonarr/Radarr including all metadata",
        "label": "Full Removal (delete everything)"
      },
      "unmonitor_and_delete": {
        "description": "Unmonitor and delete files, but keep metadata in Sonarr/Radarr",
        "label": "Unmonitor & Delete Files"
      },
      "unmonitor_only": {
        "description": "Stop monitoring the item but keep all files and metadata intact",
        "label": "Unmonitor Only (keep files)"
      }
    },
    "easy": {
      "addConditions": "Add Conditions",
      "allAdded": "All conditions have been added.",
      "and": "and",
      "cond": {
        "addedLongAgo": "were added more than",
        "largeFiles": "are larger than",
        "lowResolution": "have a resolution lower than",
        "neverWatched": "have never been watched",
        "noWatchers": "have been watched by fewer than",
        "notWatchedRecently": "haven't been watched in",
        "oldCodec": "use codec",
        "releasedBefore": "were released before",
        "smallFiles": "are smaller than",
        "watchedFewTimes": "have been watched fewer than",
        "watchedOnce": "have been watched exactly once"
      },
      "markForDeletion": "Mark for deletion",
      "ruleNamePlaceholder": "e.g., Clean up unwatched content",
      "sentenceIntro": "Build your rule as a natural language sentence.",
      "subject": {
        "all": "movies and shows",
        "movie": "movies",
        "show": "TV shows"
      },
      "subjectLabel": "Media type",
      "suffix": {
        "days": "days",
        "daysAgo": "days ago",
        "times": "times",
        "users": "users"
      },
      "that": "that",
      "thatEllipsis": "that..."
    },
    "empty": {
      "action": "Create Your First Rule",
      "description": "Create rules to automatically flag media for deletion based on watch status, age, size, and more.",
      "title": "No rules configured"
    },
    "errors": {
      "loadRules": "Failed to load rules"
    },
    "fieldPicker": {
      "close": "close",
      "common": "Common",
      "commonDesc": "Most-used fields",
      "group": "group",
      "listBadge": "list",
      "navigate": "navigate",
      "noFields": "No fields matching \"{{query}}\"",
      "readsAs": "Reads as",
      "searchAria": "Search fields",
      "searchPlaceholder": "Search fields…",
      "select": "select"
    },
    "fields": {
      "allLibraries": "All Libraries",
      "daysBeforeDeletion": "days before deletion",
      "deletionAction": "Deletion Action",
      "gracePeriod": "Grace Period",
      "libraries": "Libraries",
      "librariesHint": "Limit this rule to specific Plex libraries. Leave \"All Libraries\" selected to apply it everywhere.",
      "priority": "Priority",
      "resetSeerr": "Reset in Seerr",
      "resetSeerrDesc": "Allow users to re-request this content after deletion.",
      "ruleName": "Rule Name"
    },
    "group": {
      "addCondition": "Add condition",
      "addGroup": "Add group",
      "group": "Group",
      "match": "Match",
      "noConditions": "No conditions yet — add one below.",
      "removeGroup": "Remove group"
    },
    "header": {
      "createRule": "Create Rule",
      "subtitle": "Configure automated cleanup rules for your library",
      "title": "Rules"
    },
    "leaf": {
      "operator": "Operator",
      "removeCondition": "Remove condition"
    },
    "logic": {
      "allHint": "every condition must match",
      "allLabel": "ALL",
      "anyHint": "at least one condition must match",
      "anyLabel": "ANY",
      "noneHint": "no condition may match",
      "noneLabel": "NONE"
    },
    "plexUser": {
      "noneSynced": "No Plex users synced yet — connect Tautulli or Tracearr and run a sync.",
      "typeOrSelect": "Type or select Plex user…"
    },
    "preview": {
      "alreadyPending": "Pending",
      "calculating": "Calculating…",
      "chipEmpty": "Add a condition to preview",
      "chipLabel": "Live preview",
      "closeAria": "Close preview",
      "emptyHint": "Add conditions to see a preview",
      "failed": "Preview failed",
      "itemsWouldMatch": "items would match",
      "matchWord_one": "match",
      "matchWord_other": "match",
      "openAria": "Open live preview",
      "openItem": "Open in a new tab",
      "protected": "Protected",
      "queue": "Queue",
      "reclaimableSuffix": "{{size}} reclaimable",
      "title": "Live Preview",
      "topMatches": "Top matches by size:"
    },
    "requester": {
      "noData": "No requester data yet — run a library sync with Seerr connected.",
      "typeOrSelect": "Type or select requester…"
    },
    "tabs": {
      "custom": "Custom Builder",
      "easy": "Easy Setup",
      "templates": "Templates"
    },
    "templates": {
      "intro": "Choose a template based on your library. These are personalized suggestions.",
      "itemsCount_one": "{{count}} item",
      "itemsCount_other": "{{count}} items",
      "noneAvailable": "No suggestions available yet. Scan your library first to get personalized recommendations, or start a blank rule.",
      "orStartBlank": "Or start a blank rule →",
      "startBlank": "Start a blank rule"
    },
    "toasts": {
      "executedMsg": "\"{{name}}\" matched {{matched}} item(s), {{processed}} processed",
      "executedTitle": "Rule executed",
      "failedMsg": "Failed to run rule",
      "failedTitle": "Rule failed",
      "noMatchesMsg": "\"{{name}}\" didn't match any items",
      "noMatchesTitle": "No matches"
    },
    "user": {
      "days": "days",
      "noMatchesEnter": "No matches — press Enter to use \"{{query}}\"",
      "noneSynced": "No users synced.",
      "owner": "(owner)",
      "syncNow": "Sync now",
      "syncing": "Syncing…",
      "typeOrSelect": "Type or select user…"
    },
    "value": {
      "addPlaceholder": "add...",
      "and": "and",
      "csvPlaceholder": "value1, value2, ...",
      "max": "max",
      "min": "min"
    }
  },
  "settings": {
    "alerts": {
      "discord": {
        "urlPlaceholder": "Paste a Discord webhook URL"
      },
      "webhooks": {
        "emptyTitle": "No webhooks configured",
        "enable": "Enable this webhook",
        "eventCount_one": "{{count}} events",
        "eventCount_other": "{{count}} events",
        "lastDeliveryFailed": "last delivery failed",
        "noUrl": "No URL yet",
        "untitled": "Untitled webhook"
      }
    },
    "apiKey": {
      "confirmBody": "This will create a new key and immediately invalidate the old one. Any scripts or integrations using the current key will stop working.",
      "confirmRegenerate": "Confirm Regenerate",
      "confirmTitle": "Regenerate API Key?",
      "copyToClipboard": "Copy to clipboard",
      "description": "Required for external API access (scripts, nzb360, etc.). The web UI does not need it.",
      "hideKey": "Hide key",
      "regenerate": "Regenerate",
      "regenerateHint": "Regenerating the key will invalidate the current one immediately.",
      "regenerating": "Regenerating...",
      "revealKey": "Reveal key",
      "unavailableBody": "This install has not issued an API key. External access stays disabled until one exists.",
      "unavailableTitle": "No API key yet",
      "usageBody": "Include the key in the <1>X-Api-Key</1> header when making API requests from external tools, scripts, or apps like nzb360.",
      "usageTitle": "Usage",
      "yourKey": "Your API Key"
    },
    "automation": {
      "diskPressure": {
        "description": "Reclaim the lowest-value content only when space runs low",
        "enable": "Disk pressure cleanup",
        "freeSummary": "{{percent}}% free · {{size}}",
        "keepFree": "Keep free — soft target {{soft}}, critical {{critical}}",
        "monitoring": "Monitoring {{paths}}",
        "observeBadge": "Observe only",
        "observeHint": "Logs and notifies what it would reclaim — nothing is deleted."
      },
      "intervalShort": {
        "daily": "daily",
        "hourly": "hourly",
        "weekly": "weekly"
      },
      "librarySync": {
        "description": "Automatically pull new movies and shows from {{name}} into Prunerr",
        "enable": "Automatic {{name}} sync",
        "enableHint": "Refresh the library so new items appear without clicking “Sync Library”",
        "title": "{{name}} library sync"
      },
      "mediaServerSync": "{{name}} sync",
      "notScheduled": "Not scheduled",
      "scan": {
        "autoProcessHint": "Delete queued items once the grace period expires",
        "enableHint": "Evaluate the library against your rules on a schedule"
      },
      "syncSummary": "{{time}} {{interval}}"
    },
    "backup": {
      "confirmImport": "Confirm Import",
      "confirmImportBody": "Importing will overwrite all current settings with the values from <strong>{{filename}}</strong>. This action cannot be undone.",
      "confirmImportTitle": "Confirm Import",
      "confirmRestore": "Replace my data",
      "confirmRestoreBody": "Everything currently in Prunerr — library, rules, queue and history — will be replaced by <strong>{{filename}}</strong>.",
      "confirmRestoreSafety": "Your current database is saved alongside it first, so a mistake can be undone from the data folder.",
      "confirmRestoreTitle": "Restore this backup?",
      "description": "Export settings for backup or import from a previous export",
      "downloadFull": "Download backup",
      "export": "Export Settings",
      "exportFailed": "Export failed",
      "exportHint": "Exports include all settings including service credentials. Keep the file secure.",
      "fullDownloaded": "Backup downloaded",
      "fullFailed": "Backup failed",
      "fullHint": "The entire database — library, rules, queue, history and settings. Restoring replaces everything currently in Prunerr.",
      "fullTitle": "Full backup",
      "import": "Import Settings",
      "importFailed": "Import failed: {{error}}",
      "importSuccess": "Settings imported successfully! The page will reload with new values.",
      "importing": "Importing...",
      "invalidFormat": "Invalid file format",
      "restore": "Restore",
      "restoreDone": "Database restored",
      "restoreDoneHint": "Reload the page to see the restored data.",
      "restoreFailed": "Restore failed",
      "restoring": "Restoring…",
      "settingsTitle": "Settings only"
    },
    "chips": {
      "freeSpace": "Free space {{percent}}%",
      "freeUnknown": "Free space unknown",
      "nextScan": "Next scan {{when}}",
      "noServices": "No services connected",
      "scanningOff": "Scanning off",
      "servicesUp": "{{up}} of {{total}} services up"
    },
    "common": {
      "back": "Back",
      "cancel": "Cancel",
      "done": "Done",
      "sending": "Sending..."
    },
    "connections": {
      "connect": "Connect",
      "docs": "Open {{name}} documentation",
      "edit": "Edit",
      "firstRun": {
        "body": "Connect {{name}} and Prunerr can read your library. Add Sonarr or Radarr when you want it to actually delete things — scanning stays off until then.",
        "connect": "Connect {{name}}",
        "title": "Nothing is connected yet"
      },
      "notConnected": "Not connected",
      "notes": {
        "mediaServer": "Library data and watch status",
        "overseerr": "Resets requests on deletion",
        "radarr": "Needed to delete movies",
        "sonarr": "Needed to delete TV shows",
        "unraid": "Array and disk monitoring"
      },
      "roles": {
        "optional": "Optional",
        "recommended": "Recommended"
      },
      "sections": {
        "overseerrDescription": "Clears the request when Prunerr deletes what it asked for",
        "sonarrRadarr": "Sonarr & Radarr",
        "sonarrRadarrDescription": "Prunerr deletes through these — without them it can only report",
        "unraidDescription": "Array and disk monitoring — feeds the disk-pressure gauge"
      },
      "status": {
        "unreachable": "Unreachable",
        "verifying": "Verifying…"
      },
      "testAll": "Test all connections",
      "testAllEmpty": "Nothing is configured to test yet",
      "watchHistory": {
        "direct": "{{name}} direct",
        "freshHint": "Optional — pick one to unlock watch-count rules",
        "hint": "Play counts and watched status · {{days}} day lookback",
        "mismatch": "{{provider}} only resolves Plex item ids, so on {{name}} every item reports zero plays — and zero-play items are exactly what the rules engine deletes. Switch to “{{name}} direct”.",
        "plexOnly": "{{provider}} reads Plex item ids, so it needs a Plex media server.",
        "saveFailed": "Could not save the watch history provider",
        "title": "Watch history provider"
      }
    },
    "diskPressure": {
      "criticalAuto": {
        "description": "Bypasses the grace period when critically low. Protected items are always skipped.",
        "title": "Auto-delete immediately on critical pressure"
      },
      "deletionAction": {
        "label": "Deletion action"
      },
      "deletionActions": {
        "deleteFilesOnly": "Delete files only",
        "fullRemoval": "Full removal",
        "unmonitorAndDelete": "Unmonitor & delete files",
        "unmonitorOnly": "Unmonitor only (keep files)"
      },
      "enable": {
        "description": "Monitors real free space and acts only when below your target"
      },
      "knobs": {
        "bufferGb": "Buffer (GB)",
        "intervalMin": "Check interval (min)",
        "maxGbPerRun": "Max GB per run",
        "maxItemsPerRun": "Max items per run",
        "softGraceDays": "Soft grace (days)",
        "unwatchedDays": "Unwatched threshold (days)"
      },
      "observeOnly": {
        "title": "Observe-only mode"
      },
      "paths": {
        "add": "Add path",
        "remove": "Remove path",
        "title": "Monitored paths"
      },
      "target": {
        "criticalThreshold": "critical threshold ({{unit}}) — below this, reclaim with no grace",
        "percentOfDisk": "% of disk",
        "softTarget": "soft target",
        "title": "Keep free"
      },
      "title": "Disk Pressure"
    },
    "display": {
      "dateFormat": {
        "absoluteShort": "Absolute",
        "isoShort": "ISO",
        "label": "Date Format",
        "relativeShort": "Relative"
      },
      "description": "Customize how dates, times, and sizes are shown",
      "fileSizeUnit": {
        "autoShort": "Auto",
        "gbShort": "GB",
        "label": "File Size Unit",
        "mbShort": "MB",
        "tbShort": "TB"
      },
      "timeFormat": {
        "h12Short": "12-hour",
        "h24Short": "24-hour",
        "label": "Time Format"
      }
    },
    "exclusionPatterns": {
      "activeCount_one": "{{count}} active pattern. Items matching any pattern will be skipped during rule evaluation.",
      "activeCount_other": "{{count}} active pattern. Items matching any pattern will be skipped during rule evaluation.",
      "add": "Add Pattern",
      "description": "Items matching these patterns will be automatically protected from deletion during scans",
      "edit": "Edit pattern",
      "emptyBody": "Add one to permanently shield titles — e.g. anything containing “Christmas”.",
      "emptyTitle": "No patterns yet",
      "fieldLabel": "Field",
      "fields": {
        "title": "Title",
        "type": "Type"
      },
      "hitsUnknown": "Match count is calculated on the next scan",
      "noValue": "No value yet",
      "operatorLabel": "Operator",
      "operators": {
        "contains": "Contains",
        "endsWith": "Ends with",
        "equals": "Equals",
        "regex": "Regex",
        "startsWith": "Starts with"
      },
      "remove": "Remove",
      "title": "Exclusion Patterns",
      "typePlaceholder": "movie or show",
      "valueLabel": "Value",
      "valuePlaceholder": "Pattern to match..."
    },
    "firstRun": {
      "automation": {
        "action": "Go to Connections",
        "body": "You can set schedules now — they stay dormant until {{name}} is connected.",
        "noPaths": "No monitored paths yet — add one to watch free space",
        "title": "Waiting on a {{name}} connection"
      }
    },
    "footnote": {
      "staged": "Edits are staged locally — nothing is written until you save."
    },
    "haptics": {
      "description": "Vibration on touch interactions — supported mobile devices only",
      "enable": "Enable haptics",
      "enableDescription": "A subtle tap when opening, closing, and dismissing sheets. Saved per device."
    },
    "header": {
      "eyebrow": "Configuration",
      "title": "Settings"
    },
    "libraryExclusions": {
      "empty": "No libraries found. Make sure {{server}} is configured and connected.",
      "emptyFresh": "Connect {{server}} and your libraries will appear here — everything is included by default.",
      "emptyTitle": "No libraries loaded",
      "includedCountServer": "{{included}} of {{total}} {{server}} libraries included in scans",
      "loading": "Loading libraries from {{server}}...",
      "refresh": "Refresh libraries from {{server}}",
      "title": "Library Exclusions"
    },
    "mediaServer": {
      "description": "The server Prunerr reads your library from",
      "playbackReportingHint": "Tip: install the Playback Reporting plugin on your server. Without it only the most recent play of each item is recorded, so repeat views are missed and play counts read low.",
      "title": "Media Server"
    },
    "nav": {
      "alerts": "Alerts",
      "ariaLabel": "Settings categories",
      "automation": "Automation",
      "connections": "Connections",
      "interface": "Interface",
      "safety": "Safety",
      "sub": {
        "apiKey": "API key",
        "backupRestore": "Backup & restore",
        "discord": "Discord",
        "diskPressure": "Disk pressure",
        "displayPreferences": "Display preferences",
        "exclusionPatterns": "Exclusion patterns",
        "haptics": "Haptic feedback",
        "libraryExclusions": "Library exclusions",
        "librarySync": "Library sync",
        "mediaServer": "Media server",
        "notificationLanguage": "Notification language",
        "overseerr": "Seerr",
        "privacy": "Privacy",
        "scanSchedule": "Scan schedule",
        "sonarrRadarr": "Sonarr & Radarr",
        "unraid": "Unraid",
        "watchHistory": "Watch history",
        "webhooks": "Outbound webhooks"
      },
      "system": "System"
    },
    "notifications": {
      "discord": {
        "description": "Send notifications to a Discord channel",
        "enterUrlFirst": "Enter a webhook URL first",
        "sendFailed": "Failed to send test",
        "testFailed": "Test failed",
        "title": "Discord Webhook",
        "webhookUrl": "Webhook URL"
      },
      "language": {
        "description": "Language for outgoing notification messages",
        "title": "Notification Language"
      },
      "scan": {
        "always": "Always notify after scan",
        "flaggedOnly": "Only when items are flagged",
        "never": "Never",
        "title": "Scan Notifications"
      }
    },
    "plexSync": {
      "hourlyHint": "Sync will run at this minute past each hour",
      "intervalLabel": "Sync Interval",
      "timeHint": "Run before your scan so rules see the latest catalog",
      "timeLabel": "Sync Time"
    },
    "privacy": {
      "announcementsBody": "The same switch controls the announcements shown under What’s new in the sidebar. They are fetched from the same endpoint a few times a day with only the version number attached; with this off, none are shown.",
      "description": "What Prunerr sends outside your network, and how to stop it.",
      "exactlyWhatIsSent": "Exactly what is sent",
      "installCountBody": "Once a day, Prunerr sends a random ID and its version number so we can see how many installs are out there. Nothing about your library, your settings, your credentials or you is included, and your IP address is not stored. Switching this off deletes the random ID.",
      "installCountTitle": "Anonymous install count",
      "lastSent": "Last sent: {{when}}",
      "lockedByEnv": "Turned off for this container by TELEMETRY_ENABLED=false. Nothing is sent, and this switch cannot override it.",
      "noEndpoint": "This build has no telemetry endpoint configured, so nothing is sent regardless of this switch.",
      "notYetGenerated": "not generated yet"
    },
    "safety": {
      "effect": {
        "eligible": "Eligible for cleanup",
        "excludedLibraries": "Excluded libraries",
        "protected": "Protected",
        "title": "Effect of current rules"
      },
      "protectedNow": {
        "caption": "Titles your current rules will not touch",
        "captionEmpty": "Nothing scanned yet",
        "title": "Protected right now"
      }
    },
    "savePill": {
      "discard": "Discard",
      "save": "Save Changes",
      "saveCount_one": "Save {{count}} change",
      "saveCount_other": "Save {{count}} changes",
      "saving": "Saving...",
      "unsaved_one": "{{count}} unsaved change",
      "unsaved_other": "{{count}} unsaved changes"
    },
    "schedule": {
      "auto": {
        "title": "Automatic Scanning"
      },
      "autoProcess": {
        "title": "Auto-Process Queue"
      },
      "dayOfWeek": "Day of Week",
      "description": "Automate library scanning and cleanup",
      "hourlyHint": "Scan will run at this minute past each hour",
      "intervalLabel": "Scan Interval",
      "intervals": {
        "daily": "Once per day",
        "hourly": "Every hour (at :00)",
        "weekly": "Once per week"
      },
      "timeHint": "Scan will run at this time",
      "timeLabel": "Scan Time",
      "title": "Scan Schedule"
    },
    "search": {
      "noResults": "Nothing matches “{{query}}”. Try “webhook”, “grace”, “api key”.",
      "placeholder": "Search settings…"
    },
    "services": {
      "fields": {
        "apiKey": "API Key",
        "apiKeyOrTokenPlaceholder": "Enter API key or token",
        "token": "Token",
        "url": "URL"
      },
      "required": "Required",
      "test": {
        "button": "Test Connection",
        "connected": "Connected",
        "connectedSuccess": "Connected successfully",
        "connectionFailed": "Connection failed",
        "noConfig": "No configuration found",
        "verifying": "Verifying connection..."
      }
    },
    "summary": {
      "alertsOff": "No alerts configured",
      "alertsOn": "Discord enabled",
      "automationOff": "Scanning off",
      "automationOn": "Daily scan at {{time}}",
      "connections": "{{up}} of {{total}} connected",
      "connectionsFresh": "{{name}} not connected",
      "interface": "Dates, times and units",
      "safety_one": "{{count}} libraries excluded",
      "safety_other": "{{count}} libraries excluded",
      "system": "API key and backups"
    },
    "system": {
      "productName": "Prunerr"
    },
    "toasts": {
      "apiKeyRegenerateFailed": "Failed to regenerate API key",
      "apiKeyRegeneratedMsg": "Any scripts or integrations using the old key will need to be updated.",
      "apiKeyRegeneratedTitle": "API key regenerated",
      "copyFailed": "Failed to copy to clipboard",
      "failedSaveLibraryMsg": "Could not save library exclusions",
      "failedSavePatternsMsg": "Could not save exclusion patterns",
      "failedSaveTitle": "Failed to save",
      "librariesExcludedMsg_one": "Removed {{count}} item from excluded libraries",
      "librariesExcludedMsg_other": "Removed {{count}} items from excluded libraries",
      "librariesExcludedTitle": "Libraries excluded",
      "savedTitle": "Settings saved",
      "telemetryFailed": "Could not change that setting"
    },
    "unraidHelper": {
      "copied": "Copied",
      "copy": "Copy",
      "copyTemplate": "Copy template",
      "note": "This template creates a read-only API key with viewer permissions for monitoring array health and disk status.",
      "step1": "Go to your Unraid server: <strong>Settings → Management Access → API</strong>",
      "step2": "Click <strong>\"Add API Key\"</strong>",
      "step3": "Click <strong>\"Create from Template\"</strong>",
      "step4": "Paste the template below and click <strong>\"Continue\"</strong>",
      "step5": "Copy the generated API key and paste it above",
      "templateLabel": "API Key Template:",
      "title": "How to create an API key"
    },
    "watchHistory": {
      "description": "Connect a watch history service for tracking play counts and watched status",
      "lookback": {
        "days": "days",
        "description": "How far back to fetch watch history data",
        "title": "History Lookback"
      },
      "mediaServerDirectInfo": "No extra configuration needed — Prunerr will read history from your media server using the connection set in the Media Server section above. Install the Playback Reporting plugin for full play-count accuracy.",
      "plexDirectInfo": "No extra configuration needed — Prunerr will read history from your Plex server using the connection set in the Media Server section above. Requires the server-owner's token.",
      "providers": {
        "tautulli": {
          "fieldLabel": "API Key"
        },
        "tracearr": {
          "fieldLabel": "API Token"
        }
      },
      "title": "Watch History Provider"
    },
    "webhooks": {
      "add": "Add webhook",
      "delivered": "Delivered (HTTP {{status}})",
      "deliveryFailed": "Delivery failed",
      "description": "POST events to any URL — wire Prunerr into Home Assistant, n8n, or your own automations",
      "empty": "No webhooks configured. Add one to start sending events.",
      "enterUrlFirst": "Enter a URL first",
      "eventsLabel": "Events",
      "nameLabel": "Name (optional)",
      "remove": "Remove webhook",
      "secretLabel": "Signing secret (optional)",
      "secretPlaceholder": "Used to sign requests with X-Prunerr-Signature",
      "sendTest": "Send test",
      "title": "Outbound Webhooks"
    }
  }
}
