// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "common": {
    "language": {
      "en": "English",
      "es": "Spanish",
      "label": "Language"
    }
  }
}
